insert into Address (addressID, street, city, province, postalCode) values (44, '9839 Dottie Circle', 'Temirtau', 'QC', 'G3I 6S2');
insert into Address (addressID, street, city, province, postalCode) values (10, '15033 Caliangt Park', 'Lutian', 'NT', 'P4F 5M1');
insert into Address (addressID, street, city, province, postalCode) values (49, '07087 Walton Plaza', 'Ashiya', 'BC', 'N6T 7F9');
insert into Address (addressID, street, city, province, postalCode) values (17, '0 Gina Place', 'Gaoqiao', 'YT', 'H5R 5H3');
insert into Address (addressID, street, city, province, postalCode) values (64, '54214 Hoard Point', 'Ningtang', 'QC', 'J5R 9F4');
insert into Address (addressID, street, city, province, postalCode) values (13, '81 Vernon Place', 'Catamayo', 'NU', 'N9K 0L1');
insert into Address (addressID, street, city, province, postalCode) values (86, '4 Mockingbird Place', 'Brodarica', 'PE', 'M6U 9C5');
insert into Address (addressID, street, city, province, postalCode) values (86, '6 Forest Court', 'Mauá', 'QC', 'A9V 7P6');
insert into Address (addressID, street, city, province, postalCode) values (5, '4588 Goodland Circle', 'Khiwa', 'NT', 'S3O 2N1');
insert into Address (addressID, street, city, province, postalCode) values (51, '558 Iowa Court', 'Syevyerodonets’k', 'AB', 'M8P 8J6');
insert into Address (addressID, street, city, province, postalCode) values (43, '54 Ohio Avenue', 'Tangjiapo', 'AB', 'J0I 4K9');
insert into Address (addressID, street, city, province, postalCode) values (97, '231 Kennedy Plaza', 'Shibirghān', 'ON', 'X8O 0K5');
insert into Address (addressID, street, city, province, postalCode) values (75, '3 Manley Pass', 'Ngluwuk', 'NB', 'X3Q 0Y0');
insert into Address (addressID, street, city, province, postalCode) values (9, '01 Bultman Center', 'Waekolong', 'QC', 'P5Q 4Z9');
insert into Address (addressID, street, city, province, postalCode) values (92, '0 Fremont Court', 'Sovetskiy', 'NT', 'H4Z 5S9');
insert into Address (addressID, street, city, province, postalCode) values (28, '54497 Bonner Junction', 'Chaparral', 'NT', 'Q3X 1H4');
insert into Address (addressID, street, city, province, postalCode) values (42, '84 Mosinee Circle', 'Lampari', 'QC', 'I8R 5G9');
insert into Address (addressID, street, city, province, postalCode) values (43, '6468 Haas Alley', 'Liuliping', 'ON', 'H6N 8H1');
insert into Address (addressID, street, city, province, postalCode) values (91, '312 Carpenter Way', 'Matsumoto', 'SK', 'U8J 4Q4');
insert into Address (addressID, street, city, province, postalCode) values (88, '649 Hauk Road', 'Gaya', 'NU', 'U1P 8R6');
insert into Address (addressID, street, city, province, postalCode) values (61, '3651 Mcbride Crossing', 'Ust’-Koksa', 'NU', 'Y1Y 9K4');
insert into Address (addressID, street, city, province, postalCode) values (96, '29202 Logan Avenue', 'Āzādshahr', 'QC', 'I5R 6M0');
insert into Address (addressID, street, city, province, postalCode) values (96, '7167 Nelson Street', 'Strömsund', 'QC', 'J3C 1Q7');
insert into Address (addressID, street, city, province, postalCode) values (80, '6030 Thackeray Pass', 'Baixo Guandu', 'QC', 'G5Z 8L9');
insert into Address (addressID, street, city, province, postalCode) values (91, '16 Sunbrook Lane', 'Vale de Figueira', 'AB', 'I5V 5P3');