insert into Games (gameID, gameTitle, description, releaseDate, price, difficultyID) values (10, 'Assassin''s Creed', 'Mystery puzzle game', '8/4/2023', '$221.87', 3);
insert into Games (gameID, gameTitle, description, releaseDate, price, difficultyID) values (7, 'Overwatch', 'Sci-fi thriller', '6/11/2023', '$306.83', 1);
insert into Games (gameID, gameTitle, description, releaseDate, price, difficultyID) values (25, 'Overwatch', 'Sci-fi thriller', '6/3/2023', '$33.18', 1);
insert into Games (gameID, gameTitle, description, releaseDate, price, difficultyID) values (14, 'Call of Duty', 'Fantasy RPG', '5/18/2023', '$299.63', 3);
insert into Games (gameID, gameTitle, description, releaseDate, price, difficultyID) values (9, 'World of Warcraft', 'Horror survival', '9/14/2023', '$485.39', 2);
insert into Games (gameID, gameTitle, description, releaseDate, price, difficultyID) values (3, 'League of Legends', 'Fantasy RPG', '1/10/2024', '$321.72', 1);
insert into Games (gameID, gameTitle, description, releaseDate, price, difficultyID) values (16, 'Grand Theft Auto', 'Mystery puzzle game', '2/5/2024', '$131.90', 1);
insert into Games (gameID, gameTitle, description, releaseDate, price, difficultyID) values (18, 'Call of Duty', 'Fantasy RPG', '1/24/2024', '$42.12', 3);
insert into Games (gameID, gameTitle, description, releaseDate, price, difficultyID) values (23, 'Assassin''s Creed', 'Sci-fi thriller', '1/11/2024', '$232.12', 2);
insert into Games (gameID, gameTitle, description, releaseDate, price, difficultyID) values (22, 'Minecraft', 'Mystery puzzle game', '12/14/2023', '$458.81', 2);
insert into Games (gameID, gameTitle, description, releaseDate, price, difficultyID) values (11, 'Minecraft', 'Sci-fi thriller', '2/1/2024', '$35.54', 1);
insert into Games (gameID, gameTitle, description, releaseDate, price, difficultyID) values (22, 'Overwatch', 'Fantasy RPG', '12/29/2023', '$271.83', 2);
insert into Games (gameID, gameTitle, description, releaseDate, price, difficultyID) values (19, 'Call of Duty', 'Horror survival', '11/30/2023', '$122.92', 3);
insert into Games (gameID, gameTitle, description, releaseDate, price, difficultyID) values (22, 'World of Warcraft', 'Sci-fi thriller', '6/7/2023', '$353.70', 1);
insert into Games (gameID, gameTitle, description, releaseDate, price, difficultyID) values (5, 'World of Warcraft', 'Horror survival', '9/23/2023', '$405.76', 1);
insert into Games (gameID, gameTitle, description, releaseDate, price, difficultyID) values (23, 'Call of Duty', 'Action-packed adventure', '4/4/2023', '$384.47', 3);
insert into Games (gameID, gameTitle, description, releaseDate, price, difficultyID) values (9, 'Assassin''s Creed', 'Mystery puzzle game', '11/18/2023', '$178.38', 1);
insert into Games (gameID, gameTitle, description, releaseDate, price, difficultyID) values (21, 'Super Mario Bros.', 'Horror survival', '12/1/2023', '$363.42', 2);
insert into Games (gameID, gameTitle, description, releaseDate, price, difficultyID) values (25, 'Assassin''s Creed', 'Sci-fi thriller', '12/31/2023', '$135.10', 1);
insert into Games (gameID, gameTitle, description, releaseDate, price, difficultyID) values (19, 'The Legend of Zelda', 'Mystery puzzle game', '10/8/2023', '$61.97', 1);
insert into Games (gameID, gameTitle, description, releaseDate, price, difficultyID) values (7, 'World of Warcraft', 'Horror survival', '3/2/2023', '$113.80', 1);
insert into Games (gameID, gameTitle, description, releaseDate, price, difficultyID) values (6, 'Minecraft', 'Fantasy RPG', '11/29/2023', '$350.46', 1);
insert into Games (gameID, gameTitle, description, releaseDate, price, difficultyID) values (4, 'The Legend of Zelda', 'Horror survival', '9/16/2023', '$426.73', 1);
insert into Games (gameID, gameTitle, description, releaseDate, price, difficultyID) values (7, 'Super Mario Bros.', 'Sci-fi thriller', '6/7/2023', '$186.69', 2);
insert into Games (gameID, gameTitle, description, releaseDate, price, difficultyID) values (22, 'Grand Theft Auto', 'Mystery puzzle game', '8/30/2023', '$255.72', 3);
