insert into Positions (positionid, positionname, storeid) values (1, 'Manager', 5);
insert into Positions (positionid, positionname, storeid) values (2, 'Stock Clerk', 21);
insert into Positions (positionid, positionname, storeid) values (3, 'Manager', 8);
insert into Positions (positionid, positionname, storeid) values (4, 'Stock Clerk', 23);
insert into Positions (positionid, positionname, storeid) values (5, 'Manager', 18);
insert into Positions (positionid, positionname, storeid) values (6, 'Manager', 17);
insert into Positions (positionid, positionname, storeid) values (7, 'Cashier', 1);
insert into Positions (positionid, positionname, storeid) values (8, 'Supervisor', 24);
insert into Positions (positionid, positionname, storeid) values (9, 'Stock Clerk', 6);
insert into Positions (positionid, positionname, storeid) values (10, 'Supervisor', 23);
insert into Positions (positionid, positionname, storeid) values (11, 'Supervisor', 9);
insert into Positions (positionid, positionname, storeid) values (12, 'Stock Clerk', 23);
insert into Positions (positionid, positionname, storeid) values (13, 'Manager', 21);
insert into Positions (positionid, positionname, storeid) values (14, 'Manager', 11);
insert into Positions (positionid, positionname, storeid) values (15, 'Stock Clerk', 21);
insert into Positions (positionid, positionname, storeid) values (16, 'Supervisor', 10);
insert into Positions (positionid, positionname, storeid) values (17, 'Supervisor', 20);
insert into Positions (positionid, positionname, storeid) values (18, 'Stock Clerk', 20);
insert into Positions (positionid, positionname, storeid) values (19, 'Manager', 13);
insert into Positions (positionid, positionname, storeid) values (20, 'Manager', 14);
insert into Positions (positionid, positionname, storeid) values (21, 'Manager', 12);
insert into Positions (positionid, positionname, storeid) values (22, 'Manager', 20);
insert into Positions (positionid, positionname, storeid) values (23, 'Supervisor', 19);
insert into Positions (positionid, positionname, storeid) values (24, 'Cashier', 11);
insert into Positions (positionid, positionname, storeid) values (25, 'Manager', 1);
insert into Positions (positionid, positionname, storeid) values (26, 'Cashier', 13);
insert into Positions (positionid, positionname, storeid) values (27, 'Stock Clerk', 4);
insert into Positions (positionid, positionname, storeid) values (28, 'Manager', 2);
insert into Positions (positionid, positionname, storeid) values (29, 'Cashier', 19);
insert into Positions (positionid, positionname, storeid) values (30, 'Stock Clerk', 13);
insert into Positions (positionid, positionname, storeid) values (31, 'Manager', 8);
insert into Positions (positionid, positionname, storeid) values (32, 'Cashier', 1);
insert into Positions (positionid, positionname, storeid) values (33, 'Stock Clerk', 17);
insert into Positions (positionid, positionname, storeid) values (34, 'Manager', 5);
insert into Positions (positionid, positionname, storeid) values (35, 'Manager', 8);
insert into Positions (positionid, positionname, storeid) values (36, 'Cashier', 16);
insert into Positions (positionid, positionname, storeid) values (37, 'Stock Clerk', 7);
insert into Positions (positionid, positionname, storeid) values (38, 'Stock Clerk', 19);
insert into Positions (positionid, positionname, storeid) values (39, 'Supervisor', 23);
insert into Positions (positionid, positionname, storeid) values (40, 'Manager', 16);
insert into Positions (positionid, positionname, storeid) values (41, 'Cashier', 13);
insert into Positions (positionid, positionname, storeid) values (42, 'Stock Clerk', 18);
insert into Positions (positionid, positionname, storeid) values (43, 'Stock Clerk', 8);
insert into Positions (positionid, positionname, storeid) values (44, 'Cashier', 13);
insert into Positions (positionid, positionname, storeid) values (45, 'Manager', 19);
insert into Positions (positionid, positionname, storeid) values (46, 'Supervisor', 15);
insert into Positions (positionid, positionname, storeid) values (47, 'Cashier', 24);
insert into Positions (positionid, positionname, storeid) values (48, 'Cashier', 14);
insert into Positions (positionid, positionname, storeid) values (49, 'Cashier', 9);
insert into Positions (positionid, positionname, storeid) values (50, 'Cashier', 4);
insert into Positions (positionid, positionname, storeid) values (51, 'Cashier', 1);
insert into Positions (positionid, positionname, storeid) values (52, 'Cashier', 10);
insert into Positions (positionid, positionname, storeid) values (53, 'Cashier', 11);
insert into Positions (positionid, positionname, storeid) values (54, 'Cashier', 25);
insert into Positions (positionid, positionname, storeid) values (55, 'Cashier', 5);
insert into Positions (positionid, positionname, storeid) values (56, 'Stock Clerk', 22);
insert into Positions (positionid, positionname, storeid) values (57, 'Stock Clerk', 25);
insert into Positions (positionid, positionname, storeid) values (58, 'Manager', 2);
insert into Positions (positionid, positionname, storeid) values (59, 'Stock Clerk', 4);
insert into Positions (positionid, positionname, storeid) values (60, 'Supervisor', 8);
insert into Positions (positionid, positionname, storeid) values (61, 'Cashier', 17);
insert into Positions (positionid, positionname, storeid) values (62, 'Cashier', 14);
insert into Positions (positionid, positionname, storeid) values (63, 'Stock Clerk', 24);
insert into Positions (positionid, positionname, storeid) values (64, 'Cashier', 25);
insert into Positions (positionid, positionname, storeid) values (65, 'Cashier', 8);
insert into Positions (positionid, positionname, storeid) values (66, 'Manager', 9);
insert into Positions (positionid, positionname, storeid) values (67, 'Stock Clerk', 22);
insert into Positions (positionid, positionname, storeid) values (68, 'Cashier', 20);
insert into Positions (positionid, positionname, storeid) values (69, 'Manager', 18);
insert into Positions (positionid, positionname, storeid) values (70, 'Stock Clerk', 17);
insert into Positions (positionid, positionname, storeid) values (71, 'Supervisor', 4);
insert into Positions (positionid, positionname, storeid) values (72, 'Stock Clerk', 19);
insert into Positions (positionid, positionname, storeid) values (73, 'Manager', 22);
insert into Positions (positionid, positionname, storeid) values (74, 'Cashier', 21);
insert into Positions (positionid, positionname, storeid) values (75, 'Manager', 3);
insert into Positions (positionid, positionname, storeid) values (76, 'Supervisor', 19);
insert into Positions (positionid, positionname, storeid) values (77, 'Cashier', 2);
insert into Positions (positionid, positionname, storeid) values (78, 'Stock Clerk', 6);
insert into Positions (positionid, positionname, storeid) values (79, 'Stock Clerk', 24);
insert into Positions (positionid, positionname, storeid) values (80, 'Cashier', 20);
insert into Positions (positionid, positionname, storeid) values (81, 'Supervisor', 4);
insert into Positions (positionid, positionname, storeid) values (82, 'Supervisor', 3);
insert into Positions (positionid, positionname, storeid) values (83, 'Cashier', 17);
insert into Positions (positionid, positionname, storeid) values (84, 'Manager', 15);
insert into Positions (positionid, positionname, storeid) values (85, 'Supervisor', 7);
insert into Positions (positionid, positionname, storeid) values (86, 'Stock Clerk', 9);
insert into Positions (positionid, positionname, storeid) values (87, 'Stock Clerk', 16);
insert into Positions (positionid, positionname, storeid) values (88, 'Stock Clerk', 20);
insert into Positions (positionid, positionname, storeid) values (89, 'Stock Clerk', 10);
insert into Positions (positionid, positionname, storeid) values (90, 'Manager', 2);
insert into Positions (positionid, positionname, storeid) values (91, 'Supervisor', 11);
insert into Positions (positionid, positionname, storeid) values (92, 'Cashier', 18);
insert into Positions (positionid, positionname, storeid) values (93, 'Stock Clerk', 3);
insert into Positions (positionid, positionname, storeid) values (94, 'Supervisor', 16);
insert into Positions (positionid, positionname, storeid) values (95, 'Stock Clerk', 5);
insert into Positions (positionid, positionname, storeid) values (96, 'Manager', 15);
insert into Positions (positionid, positionname, storeid) values (97, 'Stock Clerk', 21);
insert into Positions (positionid, positionname, storeid) values (98, 'Manager', 10);
insert into Positions (positionid, positionname, storeid) values (99, 'Stock Clerk', 21);
insert into Positions (positionid, positionname, storeid) values (100, 'Cashier', 11);
