insert into Position (positionID, positionName, storeID) values (1, 'Sales Associate', 33);
insert into Position (positionID, positionName, storeID) values (1, 'Sales Associate', 29);
insert into Position (positionID, positionName, storeID) values (2, 'Manager', 49);
insert into Position (positionID, positionName, storeID) values (3, 'Stock Clerk', 28);
insert into Position (positionID, positionName, storeID) values (3, 'Stock Clerk', 81);
insert into Position (positionID, positionName, storeID) values (3, 'Stock Clerk', 68);
insert into Position (positionID, positionName, storeID) values (4, 'Customer Service Representative', 80);
insert into Position (positionID, positionName, storeID) values (2, 'Manager', 1);
insert into Position (positionID, positionName, storeID) values (5, 'Cashier', 69);
insert into Position (positionID, positionName, storeID) values (1, 'Sales Associate', 16);
insert into Position (positionID, positionName, storeID) values (3, 'Stock Clerk', 28);
insert into Position (positionID, positionName, storeID) values (1, 'Sales Associate', 53);
insert into Position (positionID, positionName, storeID) values (3, 'Stock Clerk', 90);
insert into Position (positionID, positionName, storeID) values (3, 'Stock Clerk', 63);
insert into Position (positionID, positionName, storeID) values (1, 'Sales Associate', 37);
insert into Position (positionID, positionName, storeID) values (4, 'Customer Service Representative', 5);
insert into Position (positionID, positionName, storeID) values (1, 'Sales Associate', 5);
insert into Position (positionID, positionName, storeID) values (4, 'Customer Service Representative', 42);
insert into Position (positionID, positionName, storeID) values (3, 'Stock Clerk', 86);
insert into Position (positionID, positionName, storeID) values (3, 'Stock Clerk', 38);
insert into Position (positionID, positionName, storeID) values (2, 'Manager', 66);
insert into Position (positionID, positionName, storeID) values (1, 'Sales Associate', 28);
insert into Position (positionID, positionName, storeID) values (2, 'Manager', 53);
insert into Position (positionID, positionName, storeID) values (3, 'Cashier', 24);
insert into Position (positionID, positionName, storeID) values (1, 'Sales Associate', 77);
