insert into Positions (positionID, positionName, storeID) values (1, 'Sales Associate', 1);
insert into Positions (positionID, positionName, storeID) values (2, 'Stock Clerk', 1);
insert into Positions (positionID, positionName, storeID) values (3, 'Manager', 1);
insert into Positions (positionID, positionName, storeID) values (4, 'Supervisor', 1);
insert into Positions (positionID, positionName, storeID) values (1, 'Sales Associate', 2);
insert into Positions (positionID, positionName, storeID) values (2, 'Stock Clerk', 2);
insert into Positions (positionID, positionName, storeID) values (3, 'Manager', 2);
insert into Positions (positionID, positionName, storeID) values (4, 'Supervisor', 2);
insert into Positions (positionID, positionName, storeID) values (1, 'Sales Associate', 3);
insert into Positions (positionID, positionName, storeID) values (2, 'Stock Clerk', 3);
insert into Positions (positionID, positionName, storeID) values (3, 'Manager', 3);
insert into Positions (positionID, positionName, storeID) values (4, 'Supervisor', 3);
insert into Positions (positionID, positionName, storeID) values (1, 'Sales Associate', 4);
insert into Positions (positionID, positionName, storeID) values (2, 'Stock Clerk', 4);
insert into Positions (positionID, positionName, storeID) values (3, 'Manager', 4);
insert into Positions (positionID, positionName, storeID) values (4, 'Supervisor', 4);
insert into Positions (positionID, positionName, storeID) values (1, 'Sales Associate', 5);
insert into Positions (positionID, positionName, storeID) values (2, 'Stock Clerk', 5);
insert into Positions (positionID, positionName, storeID) values (3, 'Manager', 5);
insert into Positions (positionID, positionName, storeID) values (4, 'Supervisor', 5);
insert into Positions (positionID, positionName, storeID) values (1, 'Sales Associate', 6);
insert into Positions (positionID, positionName, storeID) values (2, 'Stock Clerk', 6);
insert into Positions (positionID, positionName, storeID) values (3, 'Manager', 6);
insert into Positions (positionID, positionName, storeID) values (4, 'Supervisor', 6);
insert into Positions (positionID, positionName, storeID) values (1, 'Sales Associate', 7);
insert into Positions (positionID, positionName, storeID) values (2, 'Stock Clerk', 7);
insert into Positions (positionID, positionName, storeID) values (3, 'Manager', 7);
insert into Positions (positionID, positionName, storeID) values (4, 'Supervisor', 7);
insert into Positions (positionID, positionName, storeID) values (1, 'Sales Associate', 8);
insert into Positions (positionID, positionName, storeID) values (2, 'Stock Clerk', 8);
insert into Positions (positionID, positionName, storeID) values (3, 'Manager', 8);
insert into Positions (positionID, positionName, storeID) values (4, 'Supervisor', 8);
insert into Positions (positionID, positionName, storeID) values (1, 'Sales Associate', 9);
insert into Positions (positionID, positionName, storeID) values (2, 'Stock Clerk', 9);
insert into Positions (positionID, positionName, storeID) values (3, 'Manager', 9);
insert into Positions (positionID, positionName, storeID) values (4, 'Supervisor', 9);
insert into Positions (positionID, positionName, storeID) values (1, 'Sales Associate', 10);
insert into Positions (positionID, positionName, storeID) values (2, 'Stock Clerk', 10);
insert into Positions (positionID, positionName, storeID) values (3, 'Manager', 10);
insert into Positions (positionID, positionName, storeID) values (4, 'Supervisor', 10);
insert into Positions (positionID, positionName, storeID) values (1, 'Sales Associate', 11);
insert into Positions (positionID, positionName, storeID) values (2, 'Stock Clerk', 11);
insert into Positions (positionID, positionName, storeID) values (3, 'Manager', 11);
insert into Positions (positionID, positionName, storeID) values (4, 'Supervisor', 11);
insert into Positions (positionID, positionName, storeID) values (1, 'Sales Associate', 12);
insert into Positions (positionID, positionName, storeID) values (2, 'Stock Clerk', 12);
insert into Positions (positionID, positionName, storeID) values (3, 'Manager', 12);
insert into Positions (positionID, positionName, storeID) values (4, 'Supervisor', 12);
insert into Positions (positionID, positionName, storeID) values (1, 'Sales Associate', 13);
insert into Positions (positionID, positionName, storeID) values (2, 'Stock Clerk', 13);
insert into Positions (positionID, positionName, storeID) values (3, 'Manager', 13);
insert into Positions (positionID, positionName, storeID) values (4, 'Supervisor', 13);
insert into Positions (positionID, positionName, storeID) values (1, 'Sales Associate', 14);
insert into Positions (positionID, positionName, storeID) values (2, 'Stock Clerk', 14);
insert into Positions (positionID, positionName, storeID) values (3, 'Manager', 14);
insert into Positions (positionID, positionName, storeID) values (4, 'Supervisor', 14);
insert into Positions (positionID, positionName, storeID) values (1, 'Sales Associate', 15);
insert into Positions (positionID, positionName, storeID) values (2, 'Stock Clerk', 15);
insert into Positions (positionID, positionName, storeID) values (3, 'Manager', 15);
insert into Positions (positionID, positionName, storeID) values (4, 'Supervisor', 15);
insert into Positions (positionID, positionName, storeID) values (1, 'Sales Associate', 16);
insert into Positions (positionID, positionName, storeID) values (2, 'Stock Clerk', 16);
insert into Positions (positionID, positionName, storeID) values (3, 'Manager', 16);
insert into Positions (positionID, positionName, storeID) values (4, 'Supervisor', 16);
insert into Positions (positionID, positionName, storeID) values (1, 'Sales Associate', 17);
insert into Positions (positionID, positionName, storeID) values (2, 'Stock Clerk', 17);
insert into Positions (positionID, positionName, storeID) values (3, 'Manager', 17);
insert into Positions (positionID, positionName, storeID) values (4, 'Supervisor', 17);
insert into Positions (positionID, positionName, storeID) values (1, 'Sales Associate', 18);
insert into Positions (positionID, positionName, storeID) values (2, 'Stock Clerk', 18);
insert into Positions (positionID, positionName, storeID) values (3, 'Manager', 18);
insert into Positions (positionID, positionName, storeID) values (4, 'Supervisor', 18);
insert into Positions (positionID, positionName, storeID) values (1, 'Sales Associate', 19);
insert into Positions (positionID, positionName, storeID) values (2, 'Stock Clerk', 19);
insert into Positions (positionID, positionName, storeID) values (3, 'Manager', 19);
insert into Positions (positionID, positionName, storeID) values (4, 'Supervisor', 19);
insert into Positions (positionID, positionName, storeID) values (1, 'Sales Associate', 20);
insert into Positions (positionID, positionName, storeID) values (2, 'Stock Clerk', 20);
insert into Positions (positionID, positionName, storeID) values (3, 'Manager', 20);
insert into Positions (positionID, positionName, storeID) values (4, 'Supervisor', 20);
insert into Positions (positionID, positionName, storeID) values (1, 'Sales Associate', 21);
insert into Positions (positionID, positionName, storeID) values (2, 'Stock Clerk', 21);
insert into Positions (positionID, positionName, storeID) values (3, 'Manager', 21);
insert into Positions (positionID, positionName, storeID) values (4, 'Supervisor', 21);
insert into Positions (positionID, positionName, storeID) values (1, 'Sales Associate', 22);
insert into Positions (positionID, positionName, storeID) values (2, 'Stock Clerk', 22);
insert into Positions (positionID, positionName, storeID) values (3, 'Manager', 22);
insert into Positions (positionID, positionName, storeID) values (4, 'Supervisor', 22);
insert into Positions (positionID, positionName, storeID) values (1, 'Sales Associate', 23);
insert into Positions (positionID, positionName, storeID) values (2, 'Stock Clerk', 23);
insert into Positions (positionID, positionName, storeID) values (3, 'Manager', 23);
insert into Positions (positionID, positionName, storeID) values (4, 'Supervisor', 23);
insert into Positions (positionID, positionName, storeID) values (1, 'Sales Associate', 24);
insert into Positions (positionID, positionName, storeID) values (2, 'Stock Clerk', 24);
insert into Positions (positionID, positionName, storeID) values (3, 'Manager', 24);
insert into Positions (positionID, positionName, storeID) values (4, 'Supervisor', 24);
insert into Positions (positionID, positionName, storeID) values (1, 'Sales Associate', 25);
insert into Positions (positionID, positionName, storeID) values (2, 'Stock Clerk', 25);
insert into Positions (positionID, positionName, storeID) values (3, 'Manager', 25);
insert into Positions (positionID, positionName, storeID) values (4, 'Supervisor', 25);