insert into Position (positionID, positionName, storeID) values (58, 'Sales Associate', 33);
insert into Position (positionID, positionName, storeID) values (80, 'Sales Associate', 29);
insert into Position (positionID, positionName, storeID) values (57, 'Manager', 49);
insert into Position (positionID, positionName, storeID) values (86, 'Stock Clerk', 28);
insert into Position (positionID, positionName, storeID) values (86, 'Stock Clerk', 81);
insert into Position (positionID, positionName, storeID) values (18, 'Stock Clerk', 68);
insert into Position (positionID, positionName, storeID) values (86, 'Customer Service Representative', 80);
insert into Position (positionID, positionName, storeID) values (43, 'Manager', 1);
insert into Position (positionID, positionName, storeID) values (8, 'Cashier', 69);
insert into Position (positionID, positionName, storeID) values (2, 'Sales Associate', 16);
insert into Position (positionID, positionName, storeID) values (30, 'Stock Clerk', 28);
insert into Position (positionID, positionName, storeID) values (96, 'Sales Associate', 53);
insert into Position (positionID, positionName, storeID) values (74, 'Stock Clerk', 90);
insert into Position (positionID, positionName, storeID) values (90, 'Stock Clerk', 63);
insert into Position (positionID, positionName, storeID) values (99, 'Sales Associate', 37);
insert into Position (positionID, positionName, storeID) values (3, 'Customer Service Representative', 5);
insert into Position (positionID, positionName, storeID) values (67, 'Sales Associate', 5);
insert into Position (positionID, positionName, storeID) values (56, 'Customer Service Representative', 42);
insert into Position (positionID, positionName, storeID) values (72, 'Stock Clerk', 86);
insert into Position (positionID, positionName, storeID) values (17, 'Stock Clerk', 38);
insert into Position (positionID, positionName, storeID) values (32, 'Manager', 66);
insert into Position (positionID, positionName, storeID) values (7, 'Sales Associate', 28);
insert into Position (positionID, positionName, storeID) values (51, 'Manager', 53);
insert into Position (positionID, positionName, storeID) values (45, 'Cashier', 24);
insert into Position (positionID, positionName, storeID) values (5, 'Sales Associate', 77);
