insert into Position (positionID, positionName, storeID) values (1, 'Sales Associate', 14);
insert into Position (positionID, positionName, storeID) values (1, 'Sales Associate', 25);
insert into Position (positionID, positionName, storeID) values (2, 'Manager', 10);
insert into Position (positionID, positionName, storeID) values (3, 'Stock Clerk', 2);
insert into Position (positionID, positionName, storeID) values (3, 'Stock Clerk', 8);
insert into Position (positionID, positionName, storeID) values (3, 'Stock Clerk', 6);
insert into Position (positionID, positionName, storeID) values (4, 'Customer Service Representative', 22);
insert into Position (positionID, positionName, storeID) values (2, 'Manager', 1);
insert into Position (positionID, positionName, storeID) values (5, 'Cashier', 13);
insert into Position (positionID, positionName, storeID) values (1, 'Sales Associate', 16);
insert into Position (positionID, positionName, storeID) values (3, 'Stock Clerk', 2);
insert into Position (positionID, positionName, storeID) values (1, 'Sales Associate', 3);
insert into Position (positionID, positionName, storeID) values (3, 'Stock Clerk', 9);
insert into Position (positionID, positionName, storeID) values (3, 'Stock Clerk', 17);
insert into Position (positionID, positionName, storeID) values (1, 'Sales Associate', 23);
insert into Position (positionID, positionName, storeID) values (4, 'Customer Service Representative', 5);
insert into Position (positionID, positionName, storeID) values (1, 'Sales Associate', 12);
insert into Position (positionID, positionName, storeID) values (4, 'Customer Service Representative', 21);
insert into Position (positionID, positionName, storeID) values (3, 'Stock Clerk', 12);
insert into Position (positionID, positionName, storeID) values (3, 'Stock Clerk', 3);
insert into Position (positionID, positionName, storeID) values (2, 'Manager', 6);
insert into Position (positionID, positionName, storeID) values (1, 'Sales Associate', 11);
insert into Position (positionID, positionName, storeID) values (2, 'Manager', 3);
insert into Position (positionID, positionName, storeID) values (3, 'Cashier', 15);
insert into Position (positionID, positionName, storeID) values (1, 'Sales Associate', 7);
